"use client";

import { useEffect, useState } from "react";

type SourceDraft = { id?: string; title: string; publisher?: string; url: string; publishedAt?: string; accessedAt?: string; role: string; reliabilityNote?: string; keyFacts: string[] };
const emptySource = (): SourceDraft => ({ title: "", publisher: "", url: "", publishedAt: "", accessedAt: new Date().toISOString().slice(0, 10), role: "FACT_CHECK", reliabilityNote: "", keyFacts: [] });

export function SourceEditor({ articleId }: { articleId: string }) {
  const [sources, setSources] = useState<SourceDraft[]>([]); const [draft, setDraft] = useState<SourceDraft>(emptySource); const [notice, setNotice] = useState<string>();
  useEffect(() => {
    let active = true;
    void fetch(`/api/admin/articles/${articleId}/sources`).then(async (response) => ({ response, data: await response.json() as SourceDraft[] | { error?: string } })).then(({ response, data }) => { if (!active) return; if (response.ok) setSources(data as SourceDraft[]); else setNotice((data as { error?: string }).error || "加载来源失败"); }).catch(() => { if (active) setNotice("加载来源失败"); });
    return () => { active = false; };
  }, [articleId]);
  function change(field: Exclude<keyof SourceDraft, "keyFacts">, value: string) { setDraft((current) => ({ ...current, [field]: value })); }
  async function save() { setNotice(undefined); const response = await fetch(`/api/admin/articles/${articleId}/sources`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, keyFacts: draft.keyFacts.map((fact) => fact.trim()).filter(Boolean) }) }); const data = await response.json() as SourceDraft | { error?: string }; if (!response.ok) { setNotice((data as { error?: string }).error || "保存来源失败"); return; } setSources((current) => { const saved = data as SourceDraft; return [...current.filter((source) => source.id !== saved.id), saved]; }); setDraft(emptySource()); setNotice("来源已保存"); }
  async function remove(sourceId: string) { const response = await fetch(`/api/admin/articles/${articleId}/sources/${sourceId}`, { method: "DELETE" }); if (!response.ok) { const data = await response.json() as { error?: string }; setNotice(data.error || "删除来源失败"); return; } setSources((current) => current.filter((source) => source.id !== sourceId)); if (draft.id === sourceId) setDraft(emptySource()); setNotice("来源已删除"); }
  return <div className="admin-panel"><h2>来源</h2><p>记录可追溯事实；来源不会暴露到公共文章页。</p><label>来源标题<input aria-label="来源标题" value={draft.title} onChange={(event) => change("title", event.target.value)} /></label><label>发布者<input value={draft.publisher || ""} onChange={(event) => change("publisher", event.target.value)} /></label><label>来源 URL<input aria-label="来源 URL" type="url" value={draft.url} onChange={(event) => change("url", event.target.value)} /></label><label>发布日<input aria-label="发布日" type="date" value={draft.publishedAt || ""} onChange={(event) => change("publishedAt", event.target.value)} /></label><label>来源角色<input aria-label="来源角色" value={draft.role} onChange={(event) => change("role", event.target.value)} /></label><label>可信度说明<textarea aria-label="可信度说明" value={draft.reliabilityNote || ""} onChange={(event) => change("reliabilityNote", event.target.value)} /></label><label>关键事实<textarea aria-label="关键事实" value={draft.keyFacts.join("\n")} placeholder="每行一条" onChange={(event) => setDraft((current) => ({ ...current, keyFacts: event.target.value.split("\n") }))} /></label><button type="button" onClick={save}>保存来源</button>{draft.id ? <button type="button" onClick={() => setDraft(emptySource())}>新增来源</button> : null}{sources.map((source) => <article key={source.id}><h3>{source.title}</h3><p>{source.publisher || "未注明发布者"} · {source.role}</p><a href={source.url} target="_blank" rel="noreferrer">查看来源</a>{source.reliabilityNote ? <p>{source.reliabilityNote}</p> : null}{source.keyFacts.length ? <ul>{source.keyFacts.map((fact) => <li key={fact}>{fact}</li>)}</ul> : null}<button type="button" onClick={() => setDraft({ ...source, publishedAt: source.publishedAt?.slice(0, 10), accessedAt: source.accessedAt?.slice(0, 10) })}>编辑</button><button type="button" onClick={() => source.id && void remove(source.id)}>删除来源</button></article>)}{notice ? <p role="status">{notice}</p> : null}</div>;
}
