import { createHash } from "node:crypto";
import type { Prisma, PrismaClient } from "@prisma/client";
import { articleUnderstandingSchema, calibrationNotesSchema, finalQualityReviewSchema, fullScriptSchema, instructionalQualityReviewSchema, languageLearningMapSchema, lessonDesignRationaleSchema, narrativePlanSchema, qualityEvidenceListSchema, sentenceAnalysisSchema, teacherPerformancePlanSchema, teachingBeatPlanSchema } from "./schemas";

export type CodexGenerationArtifacts = {
  promptVersions: Record<string, string>;
  articleUnderstanding: unknown;
  narrativePlan: unknown;
  sentenceAnalysis: unknown;
  languageLearningMap: unknown;
  lessonDesignRationale: unknown;
  teachingBeatPlan: unknown;
  teacherPerformancePlan: unknown;
  fullScriptDraft: unknown;
  englishTeachingEdit: unknown;
  humanVoiceEdit: unknown;
  finalQualityReview: unknown;
  instructionalQualityReview: unknown;
  qualityEvidence: unknown;
  calibrationNotes: unknown;
  repairHistory: unknown;
  finalScript: unknown;
};

function inputHash(input: unknown) { return createHash("sha256").update(JSON.stringify(input)).digest("hex"); }

/** Saves artifacts already generated by Codex. This module never calls an LLM. */
export async function saveCodexGeneration(db: PrismaClient, articleId: string, input: unknown, artifacts: CodexGenerationArtifacts, options: { model?: string; manuallyEdited?: boolean } = {}) {
  articleUnderstandingSchema.parse(artifacts.articleUnderstanding);
  narrativePlanSchema.parse(artifacts.narrativePlan);
  sentenceAnalysisSchema.parse(artifacts.sentenceAnalysis);
  languageLearningMapSchema.parse(artifacts.languageLearningMap);
  lessonDesignRationaleSchema.parse(artifacts.lessonDesignRationale);
  teachingBeatPlanSchema.parse(artifacts.teachingBeatPlan);
  teacherPerformancePlanSchema.parse(artifacts.teacherPerformancePlan);
  finalQualityReviewSchema.parse(artifacts.finalQualityReview);
  const instructionalQualityReview = instructionalQualityReviewSchema.parse(artifacts.instructionalQualityReview);
  const qualityEvidence = qualityEvidenceListSchema.parse(artifacts.qualityEvidence);
  calibrationNotesSchema.parse(artifacts.calibrationNotes);
  const requiredEvidence = Object.keys(instructionalQualityReview.scores);
  const evidenceDimensions = new Set(qualityEvidence.map((evidence) => evidence.dimension));
  if (requiredEvidence.some((dimension) => !evidenceDimensions.has(dimension))) throw new Error("instructional quality review is missing evidence");
  const repairRequired = instructionalQualityReview.blocking || Object.values(instructionalQualityReview.scores).some((score) => score < 4);
  const finalScript = fullScriptSchema.parse(artifacts.finalScript);
  const version = ((await db.courseScriptGeneration.aggregate({ where: { articleId }, _max: { version: true } }))._max.version ?? 0) + 1;
  return db.courseScriptGeneration.create({ data: {
    articleId, version, status: "NEEDS_REVIEW", currentStage: repairRequired ? "REPAIR_REQUIRED" : "NEEDS_REVIEW", promptVersion: artifacts.promptVersions.SCRIPT_DRAFT || "codex-direct/course-full-script-v1", promptVersions: artifacts.promptVersions as Prisma.InputJsonValue, model: options.model || "Codex", inputHash: inputHash(input), manuallyEdited: options.manuallyEdited ?? false,
    articleUnderstanding: artifacts.articleUnderstanding as Prisma.InputJsonValue, narrativePlan: artifacts.narrativePlan as Prisma.InputJsonValue, sentenceAnalysis: artifacts.sentenceAnalysis as Prisma.InputJsonValue, languageLearningMap: artifacts.languageLearningMap as Prisma.InputJsonValue, lessonDesignRationale: artifacts.lessonDesignRationale as Prisma.InputJsonValue, teachingBeatPlan: artifacts.teachingBeatPlan as Prisma.InputJsonValue, teacherPerformancePlan: artifacts.teacherPerformancePlan as Prisma.InputJsonValue, fullScriptDraft: artifacts.fullScriptDraft as Prisma.InputJsonValue, englishTeachingEdit: artifacts.englishTeachingEdit as Prisma.InputJsonValue, humanVoiceEdit: artifacts.humanVoiceEdit as Prisma.InputJsonValue, finalQualityReview: artifacts.finalQualityReview as Prisma.InputJsonValue, instructionalQualityReview: artifacts.instructionalQualityReview as Prisma.InputJsonValue, qualityEvidence: artifacts.qualityEvidence as Prisma.InputJsonValue, calibrationNotes: artifacts.calibrationNotes as Prisma.InputJsonValue, repairHistory: artifacts.repairHistory as Prisma.InputJsonValue, finalScript: finalScript as Prisma.InputJsonValue, completedAt: new Date(),
  } });
}
