import { courseGenerationPromptInstruction } from "./schemas";

export const courseGenerationPrompts = {
  UNDERSTANDING: { version: "course-understanding/v2", text: `Understand the complete B1-B2 article before any teaching script is written. Build both a content understanding line and an English expression line: identify the core question, answer, thesis, paragraph functions, turns, evidence, limits, tone, how the author forms questions, transitions, qualifications, contrasts, references, and avoids repetition. Do not write teacher narration or final language points. ${courseGenerationPromptInstruction}` },
  NARRATIVE: { version: "course-narrative/v2", text: `Turn the article understanding into a 3-6 stage route. Each stage must change content understanding and identify natural English learning opportunities. Do not finish all content teaching before language teaching, and do not write final narration. ${courseGenerationPromptInstruction}` },
  SENTENCE_ANALYSIS: { version: "course-sentence-analysis/v2", text: `Analyze every body sentence as editorial and English-teaching material. Preserve exact IDs and original text. Provide meaning, content function, adjacent relationships, QUICK/NORMAL/DEEP content depth, language candidates across phrase, collocation, sentence pattern, discourse, reference, tone, ellipsis, and rhythm, plus likely learner confusion. Do not write scripts or fixed transitions. ${courseGenerationPromptInstruction}` },
  LESSON_DESIGN: { version: "course-lesson-design-rationale/v1", text: `Write the lessonDesignRationale for this specific article before the complete script. Explain the learner's main comprehension obstacles, highest-value English opportunities, material that looks complex but should be passed quickly, sentence groupings and reasons, where to slow down or speed up, which language points would damage rhythm if overexplained, the teacher judgment this article needs, the content and language outcomes, why it should not copy Gold examples, and the main cognitive-load risk. This is a decision record, not narration or a template. Read INSTRUCTIONAL_QUALITY_STANDARD.md and EDITORIAL_MEMORY.md. ${courseGenerationPromptInstruction}` },
  LANGUAGE_MAP: { version: "course-language-learning-map/v2", text: `Select high-value, transferable English learning moments for the complete article without a fixed quota. Prefer phrases, collocations, sentence patterns, discourse connections, reference, tone, ellipsis, and rhythm. For every point explain its task in this article, transfer value, learner problem, and how teaching returns to the article. Treat unusually low, all-single-word, or unusually high selection as a warning for Codex and human review, never as a reason to add points. Do not select points merely because they are advanced, and do not turn this into a vocabulary list. Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, and EDITORIAL_MEMORY.md. ${courseGenerationPromptInstruction}` },
  BEATS: { version: "course-teaching-beats/v2", text: `Design dual-track Teaching Beats. Each beat must have a content goal and may have a language goal, with teacher move, rhetorical function, delivery pattern, spotlight sentences, and energy. Some beats should move content quickly, some blend content and language, and only a few should spotlight language. Do not force a language point into every beat or split mechanically by sentence or paragraph. Do not write final narration. ${courseGenerationPromptInstruction}` },
  PERFORMANCE: { version: "course-teacher-performance/v2", text: `Plan only the purposeful teacher moves this article needs; there is no fixed count. Moves may make a choice, anticipate confusion, call back, compare expressions, notice tone, replay with purpose, give a light reaction, or explicitly skip low-value material. Every move must have a purpose and a specific thing to avoid. Do not replace teacher judgment with filler or catchphrases. Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, and EDITORIAL_MEMORY.md. ${courseGenerationPromptInstruction}` },
  SCRIPT_DRAFT: { version: "course-full-script/v3", text: `You are a senior English teacher and knowledge-podcast host for Chinese adult B1-B2 learners. Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, EDITORIAL_MEMORY.md, all prior plans, Gold examples, and Anti-pattern examples. Directly create one complete, continuous, TTS-ready guided-reading course from the article and all plans. The article is the context in which English learning happens: help the learner understand what the author says and notice how the author expresses it. Every original sentence must be read exactly and its basic meaning covered, but the listener must not feel sentence fields being processed. Choose structure, language points, teacher moves, and depth freely for this article; do not satisfy quotas or copy examples. Every expanded teaching moment needs a reason, every Beat should carry one main cognitive burden, and every language point must return to the article. Show real choices, anticipation, callbacks, comparisons, purposeful replays, and explicit skips; do not use catchphrases to fake a human voice. Do not add facts, stories, exercises, or tasks. ${courseGenerationPromptInstruction}` },
  ENGLISH_EDITOR: { version: "course-english-teaching-edit/v2", text: `Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, and EDITORIAL_MEMORY.md. Rewrite the complete script as an English-teaching editor. Check what the learner actually learned, whether each expanded moment is necessary, whether language points are transferable and varied beyond word meanings, whether each point comes from the original and returns to the article, whether any stage loses English learning value, and whether language teaching overwhelms the article. Output a complete revised script, not advice. ${courseGenerationPromptInstruction}` },
  HUMAN_VOICE_EDITOR: { version: "course-human-voice-edit/v2", text: `Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, and EDITORIAL_MEMORY.md. Rewrite the complete affected script as a human-voice editor. Make teacher choices, anticipate real confusion, call back earlier ideas, compare expressions, notice tone, replay with purpose, and explicitly skip low-value material. Remove broadcast-script stiffness, repeated openings, filler, fake enthusiasm, and invented experience. Human presence must come from judgment, not more colloquial particles. ${courseGenerationPromptInstruction}` },
  SCRIPT_EDIT: { version: "course-full-script-edit/v2", text: `Edit the complete guided-reading script as one whole work after the English Teaching Editor and Human Voice Editor. Preserve exact original coverage and order, strengthen both content progression and English learning value, and keep one consistent teacher. Rewrite the full affected stage or script, never patch narration by mechanically inserting fields. ${courseGenerationPromptInstruction}` },
  CRITIC: { version: "course-script-critic/v3", text: `Read INSTRUCTIONAL_QUALITY_STANDARD.md, lessonDesignRationale, EDITORIAL_MEMORY.md, and all Gold/Anti-pattern calibration notes. Critique the complete course after both editing passes. Score contentUnderstanding, languageLearningValue, contentLanguageIntegration, instructionalNecessity, languagePointSelection, depthMatching, cognitiveLoadControl, teacherJudgment, articleRhythm, spokenNaturalness, and nonTemplateQuality from 1 to 5. Every score must include positive and failure evidence with stage/beat/sentence location, excerpt when useful, reason, and required change. Apply the >=4 quality gates; do not pass on abstract praise. Mark MAJOR when the course is mainly a Chinese content podcast, language points are only definitions, stages lose English learning value, teaching does not return to the article, teacher judgment is absent, or human voice is only catchphrases. Mark BLOCKER for omissions, wrong explanations, altered originals, invented experience, wrong language teaching, or mechanical assembly. Return actionable issues, not a rewrite. ${courseGenerationPromptInstruction}` },
  REPAIR: { version: "course-full-script-repair/v2", text: `Rewrite the complete affected stage or whole guided-reading script to repair the listed issues. Preserve exact original English sentences, sentence order, sentence coverage, article progression, and useful English learning content. Restore both content understanding and English learning value, and repair teacher judgment and human presence where needed. Never patch narration by mechanically inserting fields or transitions. Return the complete revised script object. ${courseGenerationPromptInstruction}` },
} as const;

export type CourseGenerationStep = keyof typeof courseGenerationPrompts;
